engins/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from engins.views import AjoutCarView, DeleteCars, EditCarView, home

app_name = "engins"

urlpatterns = [
    path('', home, name='home'),
    path('ajout_car/', AjoutCarView, name='ajout_car'),
    path('edit_car/<int:id>', EditCarView, name='edit_car'),
    path('delete_car/<int:id>', DeleteCars, name='deletecar'),
]

gestions/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from gestions.views import Ajout_course, Ajout_employe, Ajout_mission, Ajout_projet, CoursesView, Delete_course, Delete_mission, DommageView, Edit_course, Edit_employe, Edit_mission, Edit_projet, EmployeView, Finir_mission, MissionView, ProjetView, Termine_course, print_mission_pdf

app_name = "gestions"

urlpatterns = [
    path('index_employe/', EmployeView, name='employes'),
    path('ajout_employe/', Ajout_employe, name='ajout_employe'),
    path('edit_employe/<int:id>', Edit_employe, name='edit_employe'),
    
    path('index_proj/', ProjetView, name='projets'),
    path('ajout_proj/', Ajout_projet, name='ajout_projet'),
    path('edit_proj/<int:id>', Edit_projet, name='edit_projet'),
    
    path('index_course/', CoursesView, name='courses'),
    path('ajout_course/', Ajout_course, name='ajout_course'),
    path('edit_course/<int:id>', Edit_course, name='edit_course'),
    path('delete_course/<int:id>', Delete_course, name='delete_course'),
    path('termine_course/<int:id>', Termine_course, name='termine_course'),
    
    path('index_mission/', MissionView, name='missions'),
    path('ajout_mission/', Ajout_mission, name='ajout_mission'),
    path('edit_mission/<int:id>', Edit_mission, name='edit_mission'),
    path('finir_mission/<int:id>', Finir_mission, name='finir_mission'), 
    path('print_mission_pdf/<int:id>', print_mission_pdf, name='print_mission_pdf'),
    path('delete_mission/<int:id>', Delete_mission, name='delete_mission'),
    
    path('index_dommage/', DommageView, name='dommages'),
    
]

logistics/urls.py
from django.contrib import admin
from django.urls import include, path
from parametres.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('parametre/', include('parametres.urls')),
    path('engins/', include('engins.urls')),
    path('equipements/', include('equipements.urls')),
    path('gestions/', include('gestions.urls')),
    path('auth/',include('compteuser.urls')),
    path('', index, name='index'),
]

gestions/forms.py
from django import forms

from gestions.models import Attribution, Course, Employer, Mission, Projet


class EmployeForm(forms.ModelForm):
    class Meta:
        model = Employer
        fields = [
            'nom',
            'prenom',
            'fonction',
            'email',
            'contact',
            'matricule',
            'etat',
        ]
        
class ProjetForm(forms.ModelForm):
    class Meta:
        model = Projet
        fields = [
            'sigle',
            'titre',
            'date_debut',
            'date_fin',
            'etat',
            'logo_partenaire',
            'logo_sarl',
        ]
        
class AttributionForm(forms.ModelForm):
    class Meta:
        model = Attribution
        fields = [
            'date_attribution',
        ]
        
        
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = [
            'motif',
            'depart',
            'destination',
            'date_course',
            'etat_course',
            'employe',
            'vehicule',
        ]

class MissionForm(forms.ModelForm):
    class Meta:
        model = Mission
        fields = [
            'objet',
            'reference',
            'localite',
            'matriculeLouer',
            'concessionnaire',
            'date_depart',
            'date_retour',
            'employe',
            'projet',
        ]
        

gestions/views.py
from ast import Str
import datetime
from django.contrib.staticfiles import finders
import os
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from engins.models import Engins
from gestions.forms import CourseForm, EmployeForm, ProjetForm
from django.contrib import messages
from xhtml2pdf import pisa

from gestions.models import Course, Employer, Mission, Projet
from django.template.loader import get_template, render_to_string
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='compteuser:login')
def EmployeView(request):
    employes = Employer.objects.all()
    
    context = {
        'employes':employes
    }
    return render(request, 'empl/employe.html',context)

@login_required(login_url='compteuser:login')
def Ajout_employe(request):
    form = EmployeForm()
    if request.method == 'POST':
        forms = EmployeForm(request.POST, request.FILES)
        if forms.is_valid():
            forms.save()
            messages.success(request, "Enregistrement effectué avec succèss !")
            return HttpResponseRedirect(reverse('gestions:employes'))
        else :
            messages.error(request, 'Attention ! Champs vide ou Matricule exite déja')
    
    context = {
        'form':form
    }
    
    return render(request, 'empl/ajout_emp.html',context)


@login_required(login_url='compteuser:login')
def Edit_employe(request, id= None):
    employe = Employer.objects.get(id= id)
    form = EmployeForm(request.POST or None, request.FILES or None, instance=employe)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Mise à jour effectué avec succèss !")
            return HttpResponseRedirect(reverse('gestions:employes'))
            
    context = {
        'form':form,
        'employe':employe
    }
    
    return render(request, 'empl/edit_emp.html',context)



@login_required(login_url='compteuser:login')
def ProjetView(request):
    projets = Projet.objects.all()
    
    context = {
        'projets':projets
    }
    
    return render(request, 'proj/projet.html',context)


@login_required(login_url='compteuser:login')
def Ajout_projet(request):
    form = ProjetForm()
    if request.method == 'POST':
        forms = ProjetForm(request.POST, request.FILES)
        if forms.is_valid():
            forms.save()
            messages.success(request, "Enregistrement effectué avec succèss !")
            return HttpResponseRedirect(reverse('gestions:projets'))
    
    context = {
        'form':form
    }
    
    return render(request, 'proj/ajout_proj.html',context)



@login_required(login_url='compteuser:login')
def Edit_projet(request, id =None):
    projet = Projet.objects.get(id=id)
    form = ProjetForm(request.POST or None, request.FILES or None, instance=projet)
    
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Mise à jour effectué avec succèss !")
          
    
    context = {
        'form':form,
        'projet':projet
    }
    return render(request, 'proj/edit_proj.html',context)



@login_required(login_url='compteuser:login')
def CoursesView(request):
    courses = Course.objects.order_by('-id')
    
    for course in courses :
        # print(course.id)
        time = datetime.datetime.now()
        if course.created_at.day == time.day:
            reduct = time.hour - course.created_at.hour
            if reduct >= 1 :
                course.diff = str(time.hour - course.created_at.hour) + " heurs"
            else :
                course.diff = "Moins d'une heure"
        else:
            if course.created_at.month == time.month:
                course.diff = str(time.day - course.created_at.day) + " jours"
            else:
                if course.created_at.year == time.year:
                    course.diff = str(time.month - course.created_at.month) + " mois"
                    
    context = {
        'courses':courses
    }
    
    return render(request, 'course/index.html',context)



@login_required(login_url='compteuser:login')
def Ajout_course(request):
    vehicules = Engins.objects.filter(etat = 'DISPONIBLE')
    employes = Employer.objects.filter(etat = 'EN ACTIVITE')
    
    if request.method == 'POST':
        course = Course()
        course.depart = request.POST['depart']
        course.destination = request.POST['destination']
        course.date_course = request.POST['date_course']
        course.etat_course = request.POST['etat_course']
        course.motif = request.POST['motif']
        course.employe_id = int(request.POST['employe'])
        course.vehicule_id = int(request.POST['vehicule'])
        course.save()
        
        engin = Engins.objects.get(id = course.vehicule.id)
        engin.etat = 'OCCUPE'
        engin.save()
        
        user = Employer.objects.get(id = course.employe.id)
        user.etat = 'OCCUPE'
        user.save()
        
        messages.success(request, "Enregistrement effectué avec succèss !")
        return HttpResponseRedirect(reverse('gestions:courses'))
        
    context = {
        'vehicules':vehicules,
        'employes':employes,
    }
    
    return render(request, 'course/ajout_course.html',context)



@login_required(login_url='compteuser:login')
def Edit_course(request,id =None):
    course = Course.objects.get(id= id)
    
    context = {
        'course':course
    }
    
    return render(request, 'course/edit_course.html',context)


@login_required(login_url='compteuser:login')
def Delete_course(request, id=None):
    course = Course.objects.get(id=id)
    
    engin = Engins.objects.get(id = course.vehicule.id)
    engin.etat = 'DISPONIBLE'
    engin.save()
    
    user = Employer.objects.get(id = course.employe.id)
    user.etat = 'EN ACTIVITE'
    user.save()
    
    course.delete()
    messages.success(request, "Suppression effectué avec succèss !")
    return HttpResponseRedirect(reverse('gestions:courses'))



@login_required(login_url='compteuser:login')
def Termine_course(request,id = None):
    course = Course.objects.get(id=id)
    course.etat_course = 'TERMINER'
    course.date_fin = datetime.datetime.now()
    course.save()
    
    engin = Engins.objects.get(id = course.vehicule.id)
    engin.etat = 'DISPONIBLE'
    engin.save()
    
    user = Employer.objects.get(id = course.employe.id)
    user.etat = 'EN ACTIVITE'
    user.save()
    


@login_required(login_url='compteuser:login')  
def MissionView(request):
    missions = Mission.objects.all()
    today = datetime.date.today()
    for mission in missions :        
        mission.diff = mission.date_retour.day - mission.date_depart.day
    
    
    context = {
        'missions':missions,
        'today':today
    }
    
    return render(request, 'mission/index.html', context)



@login_required(login_url='compteuser:login')
def Ajout_mission(request):
    projets = Projet.objects.filter(etat = 'EN COURS')
    employes = Employer.objects.filter(etat = 'EN ACTIVITE')
    vehicules = Engins.objects.filter(etat = 'DISPONIBLE')
    
    if request.method == 'POST':
        mission = Mission()
        if request.POST['moyen'] == 'NON' :
            mission.concessionnaire = request.POST['concessionnaire']
            mission.matriculeLouer = request.POST['matriculeLouer']
            mission.moyentransport = "VEHICULE DE LOCATION"
        elif request.POST['moyen'] == 'OUI':
            course = Course()
            course.etat_course = "EN COURS"
            course.motif = request.POST['objet']
            course.depart = request.POST['depart']
            course.destination = request.POST['destination']
            course.date_course = request.POST['date_depart']
            course.vehicule_id = request.POST['vehicule']
            course.employe_id = request.POST['chauffeur']
            course.save()
            
            engin = Engins.objects.get(id = course.vehicule.id)
            engin.etat = 'OCCUPE'
            engin.save()
            
            user = Employer.objects.get(id = course.employe.id)
            user.etat = 'OCCUPE'
            user.save()
            
            mission.course_id = course.id
            mission.moyentransport = "VEHICULE DE SERVICE"
        else:
            return HttpResponseRedirect(reverse('gestions:ajout_mission'))
   
        
        mission.objet = request.POST['objet']
        mission.reference = "/AGRO-MAP/SL/"+str(datetime.datetime.now().year)+"-"+str(datetime.datetime.now().month)
        mission.date_depart = request.POST['date_depart']
        mission.date_retour = request.POST['date_retour']
        mission.localite = request.POST['localite']
        mission.employe_id = request.POST['employe']
        mission.projet_id = request.POST['projet']
        mission.etat_mission = "EN COURS"
        mission.save()
        user = Employer.objects.get(id = mission.employe.id)
        user.etat = 'OCCUPE'
        user.save()
        messages.success(request, "Mission enregistrer avec succèss !")
        return HttpResponseRedirect(reverse('gestions:missions'))
    
        
    context = {
        'projets':projets,
        'employes':employes,
        'vehicules':vehicules,
        
    }
    
    return render(request, 'mission/ajout_mission.html', context)
            


@login_required(login_url='compteuser:login')
def Edit_mission(request, id= None):
    mission = Mission.objects.get(id= id)
    projets = Projet.objects.filter(etat = 'EN COURS')
    employes = Employer.objects.filter(etat = 'EN ACTIVITE')
    vehicules = Engins.objects.filter(etat = 'DISPONIBLE')
    
    context = {
        "mission":mission,
        "projets":projets,
        "employes":employes,
        "vehicules":vehicules
    }
    

gestions/templates/course/ajout_course.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">ENREGISTRER UNE COURSE</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
       <div class="col-12"> 
        <div class="card">
            <div class="card-body">
                      <div class="card">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                          <div class="card-body">
                            <h4 class="card-title">FORMULAIRE </h4>
                            <div class="form-group row">
                              <label
                                for="fname"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Lieu depart </label
                              >
                              <div class="col-sm-9">
                                <input type="text" name="depart" class="form-control" required>
                              </div>
                            </div>
                            <div class="form-group row">
                              <label
                                for="lname"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Destination</label
                              >
                              <div class="col-sm-9">
                                <input type="text" name="destination" class="form-control" required>
                              </div>
                            </div>
                            <div class="form-group row">
                              <label
                                for="lname"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Date de la course</label
                              >
                              <div class="col-sm-9">
                                <input type="date" name="date_course" class="form-control" required>
                              </div>
                            </div>
                            <div class="form-group row">
                                <label
                                  for="cono1"
                                  class="col-sm-3 text-end control-label col-form-label"
                                  >Etat</label
                                >
                                <div class="col-sm-9">
                                    <select class="select2 form-select shadow-none" name="etat_course" style="width: 100%; height: 36px" required>
                                        <option value="EN COURS"> EN COURS </option>
                                        <option value="TERMINER"> TERMINER </option>
                                    </select>
                                  </div>
                            </div> 
                            <div class="form-group row">
                              <label
                                for="cono1"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Utilisateur</label
                              >
                              <div class="col-sm-9">
                                <select class="select2 form-select shadow-none" name="employe" style="width: 100%; height: 36px" required>
                                    {% for employe in employes %}
                                        <option value="{{employe.id}}"> {{employe.nom}} {{employe.prenom}} </option>
                                    {% endfor %}
                                </select>
                              </div>

                            </div>
                            
                            <div class="form-group row">
                              <label
                                for="cono1"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Engin utilisé</label
                              >
                              <div class="col-sm-9">
                                <select class="select2 form-select shadow-none" name="vehicule" style="width: 100%; height: 36px" required>
                                    {% for vehicule in vehicules %}
                                        <option value="{{vehicule.id}}"> {{vehicule.matricule}} </option>
                                    {% endfor %}
                                </select>
                              </div>
                            </div>                            
                            <div class="form-group row">
                              <label
                                for="cono1"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Motif</label
                              >
                              <div class="col-sm-9">
                                <textarea class="form-control" name="motif" rows="5" required></textarea>
                              </div>
                            </div>
                          </div>
                        
                      </div>
                    </div>  
                    <div class="border-top">
                        <div class="card-body">
                          <button type="submit" class="btn btn-primary form-control">
                            Valider
                          </button>
                        </div>
                    </div>
                </form>
                </div>
      
    </div>
</div>
</div>

{% endblock %}

gestions/templates/course/edit_course.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">DETAILS COURSE</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">

            <div class="row">
                <h4>INFO COURS</h4>
                <div class="col-md-6 mt-3" >
                    <strong>LIEU DE DEPART : {{course.depart}}</strong> <br>
                    <strong>DESTINATION  : {{course.destination}}</strong><br>
                    <strong>DATE DE LA COURSE : {{course.date_course}}</strong><br>
                    <strong>COURSE ACHEVEE LE : {{course.date_fin}}</strong><br>
                    <strong>ETAT : {{course.etat_course}}</strong><br>
                </div>
                <div class="col-md-4">
                    <h5>Motif</h5>
                    {{course.motif}}
                </div>
                <div class="col-md-2 mt-3" >
                    <a href="{% url 'gestions:delete_course' course.id %}" class="btn btn-danger btn-sm">SUPPRIMER COURSE </a>  
                </div>
          
            </div>
            
        </div>
      </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">

            <div class="row">
                <h4>AUTRES INFOS</h4>
                <div class="col-md-2">
                    {% if course.vehicule.engin_image %}
                        <img src="http://127.0.0.1:8000/static{{course.vehicule.engin_image.url}}" class="mr-2" alt="Profile Page" width="200px" height="200px" style="border: 1px solid #ddd;">
                    {% else %}
                    <img src="" class="mr-2" alt="NO IMAGE" width="200px" height="200px" style="border: 1px solid #ddd;">
                    {% endif %}
                    
                </div>
                <div class="col-md-6 mt-3" >
                    <strong>MARQUE : {{course.vehicule.marque}}</strong> <br>
                    <strong>MODEL : {{course.vehicule.model}}</strong><br>
                    <strong>MATRICULE : {{course.vehicule.matricule}}</strong><br>
                    <strong>NUMERO DE CHARSIS : {{course.vehicule.numcharsis}}</strong><br>
                </div>

                <div class="col-md-4 mt-3" >
                    <h6><u>Utilisateur </u></h6>
                    <strong>NOM : {{course.employe.nom}}</strong> <br>
                    <strong>PRENOMS : {{course.employe.prenom}}</strong><br>
                    <strong>FONCTION : {{course.employe.fonction}}</strong><br>
                    <strong>CONTACT : {{course.employe.contact}}</strong><br>
                </div>
          
            </div>
            
        </div>
      </div>
    </div>
</div>




{% endblock %}

gestions/templates/course/index.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">COURSES</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="container-fluid">
 <div class="row">
    <div class="col-12"> 
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Listes des courses</h5>

        {% if messages %}
        <div class="alert alert-success text-center alert-dismissible " role="alert">
            
            <ul class="messages">
                {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                {% endfor %}
            </ul>
            
        </div>
        {% endif %}


      <div class="table-responsive">
        <a href="{% url 'gestions:ajout_course' %}" class="btn btn-primary" style="float: right; margin-right: 20px;" > Ajouter </a>
        <table id="zero_config" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th style="max-width: 100px;">UTILISATEUR</th>
              <th style="max-width: 100px;">MATRICULE</th>
              <th style="max-width: 100px;">CATEGORIE</th>
              <th style="max-width: 100px;">ETAT</th>
              <th style="max-width: 100px;">DATE DEPART</th>
              <th style="max-width: 100px;">DUREE DE LA COURSE</th>
              <th style="max-width: 100px;">DESTINATION</th>
              <th style="max-width: 100px;">ACTION</th>
            </tr>
          </thead>
          <tbody>
            {% for course in courses %}
            <tr>
                <td>{{course.employe.nom}} {{course.employe.prenom}}</td>
                <td>{{course.vehicule.matricule}}</td>
                <td>{{course.vehicule.type_engins}}</td>
                <td>{{course.etat_course}}</td>
                <td>{{course.date_course}}</td>
                {% if not course.date_fin %}
                <td>{{course.created_at | timesince}}</td>
                {% else %}
                <td> {{course.diff}} </td>
                {% endif %}
                
                <td>{{course.destination}}</td>
                <td>    
                    <a href="{% url 'gestions:edit_course' course.id %}" class="btn btn-primary btn-sm" >Voir </a>
                    {% if course.etat_course == 'EN COURS' %}
                    <a  onclick="termine_cours('{% url 'gestions:termine_course' course.id %}')" class="btn btn-danger btn-sm">Terminer </a>
                    {% endif %}
                    
                </td>
              </tr>
            {% endfor %}


          </tfoot>
        </table>
      </div>
    </div>
  </div>

  </div>
  </div>
  </div>
{% endblock %}