engins/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from engins.views import AjoutCarView, DeleteCars, EditCarView, home

app_name = "engins"

urlpatterns = [
    path('', home, name='home'),
    path('ajout_car/', AjoutCarView, name='ajout_car'),
    path('edit_car/<int:id>', EditCarView, name='edit_car'),
    path('delete_car/<int:id>', DeleteCars, name='deletecar'),
]

equipements/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from equipements.views import AccessoiresView, Ajout_equipement, Attribut_Equipement, Delete_accessoire, DeleteMateriels, Edit_accessoires, Edit_equipement, MaterielView, Restitu_equipement, Store_attribution, Update_accessoire

app_name = "equipements"

urlpatterns = [
    path('index_accessoire/', AccessoiresView, name='accesooires'),
    path('edit_accessoire/<int:id>', Edit_accessoires, name='edit_accessoire'),
    path('delete_accessoire/<int:id>', Delete_accessoire, name='delete_accessoire'),
    path('update_accessoire/', Update_accessoire, name='update_accessoire'),
    
    path('index_materiel/', MaterielView, name='materiels'),
    path('ajout_equipement/', Ajout_equipement, name='ajout_equipement'),
    path('edit_equipement/<int:id>', Edit_equipement, name='edit_equipement'),
    path('supprimer_equipement/<int:id>', DeleteMateriels, name='supprimer_equipement'),
    
    path('attribut_equipement/<int:id>', Attribut_Equipement, name='attribut_equipement'),
    path('restitu_equipement/<int:id>', Restitu_equipement, name='restitu_equipement'),
    path('store_attribution/', Store_attribution, name='store_attribution'),
    
    
]

logistics/urls.py
from django.contrib import admin
from django.urls import include, path
from parametres.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('parametre/', include('parametres.urls')),
    path('engins/', include('engins.urls')),
    path('equipements/', include('equipements.urls')),
    path('gestions/', include('gestions.urls')),
    path('auth/',include('compteuser.urls')),
    path('', index, name='index'),
]

equipements/models.py
from django.db import models

from parametres.models import Type_materiel

# Create your models here.

ETAT_MATERIELS = (
    ('FONCTIONNELLE', "FONCTIONNELLE"),
    ('ENDOMMAGE', "ENDOMMAGE"),
    ('REPARATION', "REPARATION"),
    ('ATTRIBUER', "ATTRIBUER"),
)

class Accessoire(models.Model):
    libelle = models.CharField(max_length=255 ,unique=True)
    date_achat = models.DateField()
    prix_achat = models.IntegerField(blank=True, null=True)
    quantity = models.IntegerField(default=0)
    destination = models.CharField(max_length=255)
    qty_today = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return "%s" % (self.libelle)
    
    def save(self, force_insert=False, force_update=False):
        self.libelle = self.libelle.upper()
        self.destination = self.destination.upper()
        super(Accessoire, self).save(force_insert, force_update)
        
        

class Materiel(models.Model):
    code = models.CharField(max_length=255,blank=True, null=True)
    num_serie = models.CharField(max_length=255,blank=True, null=True)
    model = models.CharField(max_length=255)
    marque = models.CharField(max_length=255)
    etat = models.CharField(max_length=255, choices=ETAT_MATERIELS, default='')
    date_achat = models.DateField()
    quantity = models.IntegerField(default=1)
    prix_achat = models.IntegerField(blank=True, null=True)
    materiel_image = models.ImageField(blank=True,null=True,upload_to="images/")
    type_materiel = models.ForeignKey(Type_materiel, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return "%s - %s" % (self.marque,self.num_serie)
    
    def save(self, force_insert=False, force_update=False):
        self.code = self.code.upper()
        self.num_serie = self.num_serie.upper()
        self.model = self.model.upper()
        self.marque = self.marque.upper()
        super(Materiel, self).save(force_insert, force_update)
    
    

equipements/forms.py
from django import forms
from equipements.models import Accessoire,Materiel



class AccessoireForm(forms.ModelForm):
    class Meta:
        model = Accessoire
        fields = [
            'libelle',
            'date_achat',
            'prix_achat',
            'quantity',
            'destination',
            'qty_today',
        ]
        

class MaterielsForm(forms.ModelForm):
    class Meta:
        model = Materiel
        fields = [
            'code',
            'num_serie',
            'marque',
            'model',
            'etat',
            'date_achat',
            'quantity',
            'prix_achat',
            'type_materiel',
            'materiel_image',
        ]

equipements/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from equipements.forms import AccessoireForm, MaterielsForm
from django.contrib import messages
from django.template.context_processors import csrf
from django.template.loader import get_template, render_to_string

from equipements.models import Accessoire, Materiel
from gestions.forms import AttributionForm
from gestions.models import Attribution, Employer
from parametres.models import Type_materiel
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='compteuser:login')
def AccessoiresView(request):
    accessoires = Accessoire.objects.all()
    form = AccessoireForm()
    error = ''
    if request.method == 'POST':
        forms = AccessoireForm(request.POST)
        if forms.is_valid():
            forms.save()
            messages.success(request, 'Enregistrement effectué avec succèss !')
        else:
            error = 'Attention ! Champs vide ou libelle exite déja'
            messages.error(request, 'Attention ! Champs vide ou libelle exite déja')
        
            
    context = {
        'accessoires':accessoires,
        'form':form,
        'error':error
    }
    
    return render(request, 'accessoires.html',context) 


@login_required(login_url='compteuser:login')
def Edit_accessoires(request,id =None):
    accessoire = Accessoire.objects.get(id= id)
    form = AccessoireForm(request.POST or None, request.FILES or None, instance=accessoire)
    context = {
        'accessoire':accessoire,
        'form':form
    }
    context.update(csrf(request))
    templateStr = render_to_string("modal/edit_accessoire.html", context)
    return JsonResponse({'templateStr':templateStr,'id':id},safe=False)

@login_required(login_url='compteuser:login')
def Update_accessoire(request):
    id = request.POST['accessoire']
    accessoire = Accessoire.objects.get(id = int(id))
    form = AccessoireForm(request.POST or None, request.FILES or None, instance=accessoire)
    form.save()
    messages.success(request, "Lélément "+accessoire.libelle+" a été modifié avec succès")
    return HttpResponseRedirect(reverse('equipements:accesooires'))
  
    
@login_required(login_url='compteuser:login')   
def Delete_accessoire(request, id = None):
    accessoire = Accessoire.objects.get(id= id)
    accessoire.delete()
    messages.success(request, "Lélément "+accessoire.libelle+" a été supprimé avec succès")
    return HttpResponseRedirect(reverse('equipements:accesooires'))


@login_required(login_url='compteuser:login')
def MaterielView(request):
    equipements = Materiel.objects.all()
    
    context = {
        'equipements':equipements
    }
    return render(request, 'materiels.html',context) 


@login_required(login_url='compteuser:login')
def Ajout_equipement(request):
    type_materiels = Type_materiel.objects.all()
    form = MaterielsForm()
    
    if request.method == 'POST':
        forms = MaterielsForm(request.POST, request.FILES)
        forms.save()
        messages.success(request, "Enregistrement effectué avec succèss !")
        return HttpResponseRedirect(reverse('equipements:materiels'))
    
    
    context = {
        'type_materiels':type_materiels,
        'form':form
    }
    
    return render(request, 'ajoutmateriel.html',context)


@login_required(login_url='compteuser:login')
def Edit_equipement(request,id= None):
    equipement = Materiel.objects.get(id= id)

        
    form = MaterielsForm(request.POST or None, request.FILES or None, instance=equipement)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Mise à jour effectué avec succèss !")
          
          
    try :        
        attribut = Attribution.objects.filter(materiel_id = id).latest('id')
        context = {
            'form':form,
            'equipement':equipement,
            'user':attribut
        }
    except Attribution.DoesNotExist :  
        context = {
            'form':form,
            'equipement':equipement,
            # 'user':attribut
        }
    
    return render(request, 'editmateriel.html',context)


@login_required(login_url='compteuser:login')
def DeleteMateriels(request, id= None):
    equipement = Materiel.objects.get(id= id)
    equipement.delete()
    messages.success(request, "Suppression effectué avec succèss !")
    return HttpResponseRedirect(reverse('equipements:materiels'))


@login_required(login_url='compteuser:login')
def Attribut_Equipement(request, id= None):
    employe = Employer.objects.filter(etat = 'EN ACTIVITE') | Employer.objects.filter(etat = 'OCCUPE')
    materiel = Materiel.objects.get(id = id)
    form = AttributionForm()
    context = {
        'materiel':materiel,
        'employes':employe,
        'form':form
    }
    context.update(csrf(request))
    templateStr = render_to_string("modal/att_form_view.html", context)
    return JsonResponse({'templateStr':templateStr,'id':id},safe=False)


@login_required(login_url='compteuser:login')
def Store_attribution(request):
    materiel = Materiel.objects.get(id = int(request.POST['equipement']))
    employe = Employer.objects.get(id= int(request.POST['employe']))
    if request.method == 'POST':
        if request.POST['date_attribution'] != '':
            attribution = Attribution()
            attribution.date_attribution = request.POST['date_attribution']
            attribution.employe_id = employe.id
            attribution.materiel_id = materiel.id
            attribution.save()
            materiel.etat = "ATTRIBUER"
            materiel.save()
            messages.success(request, "Attribution du materiel "+materiel.marque+ " a Mr "+employe.nom+"")
            return HttpResponseRedirect(reverse('equipements:materiels'))
        else:
            messages.success(request, "Un problème est subvenu lors de l'attribution réessayez.")
            return HttpResponseRedirect(reverse('equipements:materiels'))
        

@login_required(login_url='compteuser:login')
def Restitu_equipement(request, id=None):
    try:
        rendre = Attribution.objects.filter(materiel_id = id).latest('id')
        materiel = Materiel.objects.get(id = id)
        rendre.etat = True
        rendre.save()
        materiel.etat = "FONCTIONNELLE"
        materiel.save()
        
    except Attribution.DoesNotExist :
       pass 
            

equipements/templates/accessoires.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">ACCESSOIRES</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="container-fluid">
 <div class="row">
    <div class="col-12"> 
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Listes des accesooires</h5>
      {% if error == '' %}
        {% if messages %}
        <div class="alert alert-success text-center alert-dismissible " role="alert">
            
            <ul class="messages">
                {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                {% endfor %}
            </ul>
            
        </div>
        {% endif %}
    {% endif %}

    {% if error != '' %}
    <div class="alert alert-danger text-center alert-dismissible " role="alert">
       {{error}} 
    </div>
    {% endif %}
      <div class="table-responsive">
        <button type="button" class="btn btn-primary" style="float: right; margin-right: 20px;" data-bs-toggle="modal" data-bs-target="#exampleModal"> Ajouter </button>
        <table id="zero_config" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>LIBELLE</th>
              <th>DATE ACHAT</th>
              <th>PRIX ACHAT</th>
              <th>QUANTITE</th>
              <th>ENDOMMAGE</th>
              <th>DESTINATION</th>
              <th style="max-width: 100px;">ACTION</th>
            </tr>
          </thead>
          <tbody>
            {% for accessoire in accessoires %}
             <tr>
                <td>{{accessoire.libelle}}</td>
                <td>{{accessoire.date_achat}}</td>
                <td>{{accessoire.prix_achat}}</td>
                <td>{{accessoire.quantity}}</td>
                <td>{{accessoire.qty_today}}</td>
                <td>{{accessoire.destination}}</td>
                <td>    
                    <a class="btn btn-primary btn-sm" onclick="edit('{% url 'equipements:edit_accessoire' accessoire.id %}')"><i class="far fa-edit"></i> </a>
                    <a href="{% url 'equipements:delete_accessoire' accessoire.id %}" class="btn btn-danger btn-sm"> <i class="far fa-trash-alt"></i></a>
                </td>
              </tr>
            {% endfor %}
          </tfoot>
        </table>
      </div>
    </div>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Enregistrer un accessoire</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="" method="post"  id="form" enctype="multipart/form-data" novalidate>
               {% csrf_token %}
                <div class="form-group">
                    <label>Libelle</label>
                    {% render_field form.libelle type="text" class="form-control" %}
                    <span class="code_error text-danger"></span>
                </div> 
                <div class="form-group">
                    <label>date achat</label>
                    {% render_field form.date_achat type="date" class="form-control" %}
                    <span class="code_error text-danger"></span>
                </div> 
                <div class="form-group">
                    <label>prix</label>
                    {% render_field form.prix_achat  class="form-control" %}
                    <span class="code_error text-danger"></span>
                </div> 
                <div class="form-group">
                    <label>destination</label>
                    {% render_field form.destination type="text" class="form-control" %}
                    <span class="code_error text-danger"></span>
                </div> 

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Quantité</label>
                            {% render_field form.quantity  class="form-control" %}
                            <span class="code_error text-danger"></span>
                        </div> 
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Endommagé</label>
                            {% render_field form.qty_today  class="form-control" %}
                            <span class="code_error text-danger"></span>
                        </div> 
                    </div>

                </div>
           
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
          <button type="submit" class="btn btn-primary">Enregistrer</button>
        </div>
    </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="Modal" aria-hidden="true">

  </div>

  </div>
  </div>
  </div>
    
{% endblock %}

equipements/templates/editmateriel.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">DETAILS</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">

            <div class="row">
                <div class="col-md-2">
                    {% if equipement.materiel_image %}
                        <img src="http://127.0.0.1:8000/static{{equipement.materiel_image.url}}" class="mr-2" alt="Profile Page" width="200px" height="200px" style="border: 1px solid #ddd;">
                    {% else %}
                    <img src="" class="mr-2" alt="NO IMAGE" width="200px" height="200px" style="border: 1px solid #ddd;">
                    {% endif %}
                    
                </div>
                <div class="col-md-8 mt-3" >
                    <strong>CODE : {{equipement.code}}</strong> <br>
                    <strong>MARQUE : {{equipement.marque}}</strong><br>
                    <strong>MODEL : {{equipement.model}}</strong><br>
                    <strong>N° SERIE : {{equipement.num_serie}}</strong><br>
                    <strong>CATEGORIE : {{equipement.type_materiel}}</strong><br>
                    <strong>ETAT : {{equipement.etat}}</strong><br>
                    <strong>DATE ACHAT : {{equipement.date_achat}}</strong><br>
                    <strong>QUANTITE : {{equipement.quantity}}</strong><br>
                    <strong>DERNIER UTILISATEUR  : {% if user %}{{user.employe.nom}} {{user.employe.prenom}} ( {{user.employe.fonction}} ){% endif %} </strong><br>
                </div>


                    <div class="col-md-2 mt-3" >
                      {% if user.etat  == False %}
                      <a href="#" onclick="restitution('{% url 'equipements:restitu_equipement' equipement.id %}')" class="btn btn-info btn-sm">RENDRE </a>
                      {% else %}

                        {% if equipement.etat == 'FONCTIONNELLE' and equipement.quantity > 0 %}
                            <a href="#" onclick="edit('{% url 'equipements:attribut_equipement' equipement.id %}')" class="btn btn-primary btn-sm">ATTRIBUER </a>
                      {% endif %}   

                      {% endif %}
                                          
                        <a href="{% url 'equipements:supprimer_equipement' equipement.id %}" class="btn btn-danger btn-sm">SUPPRIMER </a>  
                    </div>
          
            </div>
            
        </div>
      </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
       <div class="col-12"> 
        <div class="card">
            <div class="card-body">
                <div class="row">
                    {% if messages %}
                    <div class="alert alert-success text-center alert-dismissible " role="alert">
                        
                        <ul class="messages">
                            {% for message in messages %}
                            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                            {% endfor %}
                        </ul>
                        
                    </div>
                    {% endif %}
                    <div class="col-md-6">
                      <div class="card">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                          <div class="card-body">
                            <h4 class="card-title">FORMULAIRE DE MISE A JOUR </h4>
                            <div class="form-group row">
                              <label
                                for="fname"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Code</label
                              >
                              <div class="col-sm-9">
                                {% render_field form.code type="text" class="form-control" %}
                              </div>
                            </div>
                            <div class="form-group row">
                              <label
                                for="lname"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Numéro de série</label
                              >
                              <div class="col-sm-9">
                                {% render_field form.num_serie type="text" class="form-control" %}
                              </div>
                            </div>
                            <div class="form-group row">
                              <label
                                for="lname"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Marque</label
                              >
                              <div class="col-sm-9">
                                {% render_field form.marque type="text" class="form-control" %}
                              </div>
                            </div>
                            <div class="form-group row">
                              <label
                                for="email1"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Model</label
                              >
                              <div class="col-sm-9">
                                {% render_field form.model type="text" class="form-control" %}
                              </div>
                            </div>
                            <div class="form-group row">
                              <label
                                for="cono1"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Date d'achat</label
                              >
                              <div class="col-sm-9">
                                {% render_field form.date_achat type="date" class="form-control" %}
                              </div>
                            </div>
                    
                          </div>
                        
                      </div>
                    </div>  
                    <div class="col-md-6">
                      <div class="card">
                          <div class="card-body">
                            <div class="form-group row">
                              <label
                                for="fname"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Prix</label
                              >
                              <div class="col-sm-9">
                                {% render_field form.prix_achat  class="form-control" %}
                              </div>
                            </div>
                            <div class="form-group row">
                              <label
                                for="lname"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Catégorie</label
                              >
                              <div class="col-sm-9">
                                {% render_field form.type_materiel type="text" class="form-control" %}
                              </div>
                            </div>
                            <div class="form-group row">
                              <label
                                for="lname"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Etat</label
                              >
                              <div class="col-sm-9">
                                {% render_field form.etat type="date" class="form-control" %}
                              </div>
                            </div>
                            <div class="form-group row">
                              <label
                                for="email1"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Quantité</label
                              >
                              <div class="col-sm-9">
                                {% render_field form.quantity  class="form-control" %}
                              </div>
                            </div>
                            <div class="form-group row">
                              <label
                                for="cono1"
                                class="col-sm-3 text-end control-label col-form-label"
                                >Image du matériel</label
                              >
                              <div class="col-sm-9">
                                {% render_field form.materiel_image  class="form-control" %}
                              </div>
                            </div>
                          </div>
                 
                       
                      </div>
                    </div>
                    <div class="border-top">
                        <div class="card-body">
                          <button type="submit" class="btn btn-primary form-control">
                            Mettre à jour
                          </button>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="Modal" aria-hidden="true">

    </div>
</div>
</div>


{% endblock %}

equipements/templates/materiels.html
{% extends 'base.html' %}

{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">EQUIPEMENTS</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
       <div class="col-12"> 
   <div class="card">
       <div class="card-body">
         <h5 class="card-title">Listes des equipements</h5>
         {% if messages %}
         <div class="alert alert-success text-center alert-dismissible " role="alert">
             
             <ul class="messages">
                 {% for message in messages %}
                 <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                 {% endfor %}
             </ul>
             
         </div>
         {% endif %}

         <div class="table-responsive">
           <a href="{% url 'equipements:ajout_equipement' %}" class="btn btn-primary" style="float: right; margin-right: 20px;" > Ajouter </a>
           <table id="zero_config" class="table table-striped table-bordered">
             <thead>
               <tr>
                 <th>CODE</th>
                 <th >N° SERIE</th>
                 <th >MARQUE</th>
                 <th >MODEL</th>
                 <th >DATE D'ACHAT</th>
                 <th >ETAT</th>
                 <th >CATEGORIE</th>
                 <th >ACTION</th>
               </tr>
             </thead>
             <tbody>

                {% for equipement in equipements %}
                <tr>
                    <td>{{equipement.code}}</td>
                    <td>{{equipement.num_serie}}</td>
                    <td>{{equipement.marque}}</td>
                    <td>{{equipement.model}}</td>
                    <td>{{equipement.date_achat}}</td>
                    <td style=" text-align:center;"><span {% if equipement.etat == 'FONCTIONNELLE' %}class="bg-success"{% else %} class="bg-danger" {% endif %}  style="color: white;">{{equipement.etat}}</span> </td>
                    <td>{{equipement.type_materiel}}</td>
                    <td>  
                        <a href="{% url 'equipements:edit_equipement' equipement.id %}" class="btn btn-primary btn-sm">VOIR </a>  
                    </td>
                  </tr>
                {% endfor %}

             </tfoot>
           </table>
         </div>
       </div>
     </div>
   
   

   
     </div>
     </div>
     </div>

{% endblock %}