engins/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from engins.views import AjoutCarView, DeleteCars, EditCarView, home

app_name = "engins"

urlpatterns = [
    path('', home, name='home'),
    path('ajout_car/', AjoutCarView, name='ajout_car'),
    path('edit_car/<int:id>', EditCarView, name='edit_car'),
    path('delete_car/<int:id>', DeleteCars, name='deletecar'),
]

gestions/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from gestions.views import Ajout_course, Ajout_employe, Ajout_mission, Ajout_projet, CoursesView, Delete_course, Delete_mission, DommageView, Edit_course, Edit_employe, Edit_mission, Edit_projet, EmployeView, Finir_mission, MissionView, ProjetView, Termine_course, print_mission_pdf

app_name = "gestions"

urlpatterns = [
    path('index_employe/', EmployeView, name='employes'),
    path('ajout_employe/', Ajout_employe, name='ajout_employe'),
    path('edit_employe/<int:id>', Edit_employe, name='edit_employe'),
    
    path('index_proj/', ProjetView, name='projets'),
    path('ajout_proj/', Ajout_projet, name='ajout_projet'),
    path('edit_proj/<int:id>', Edit_projet, name='edit_projet'),
    
    path('index_course/', CoursesView, name='courses'),
    path('ajout_course/', Ajout_course, name='ajout_course'),
    path('edit_course/<int:id>', Edit_course, name='edit_course'),
    path('delete_course/<int:id>', Delete_course, name='delete_course'),
    path('termine_course/<int:id>', Termine_course, name='termine_course'),
    
    path('index_mission/', MissionView, name='missions'),
    path('ajout_mission/', Ajout_mission, name='ajout_mission'),
    path('edit_mission/<int:id>', Edit_mission, name='edit_mission'),
    path('finir_mission/<int:id>', Finir_mission, name='finir_mission'), 
    path('print_mission_pdf/<int:id>', print_mission_pdf, name='print_mission_pdf'),
    path('delete_mission/<int:id>', Delete_mission, name='delete_mission'),
    
    path('index_dommage/', DommageView, name='dommages'),
    
]

logistics/urls.py
from django.contrib import admin
from django.urls import include, path
from parametres.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('parametre/', include('parametres.urls')),
    path('engins/', include('engins.urls')),
    path('equipements/', include('equipements.urls')),
    path('gestions/', include('gestions.urls')),
    path('auth/',include('compteuser.urls')),
    path('', index, name='index'),
]

gestions/forms.py
from django import forms

from gestions.models import Attribution, Course, Employer, Mission, Projet


class EmployeForm(forms.ModelForm):
    class Meta:
        model = Employer
        fields = [
            'nom',
            'prenom',
            'fonction',
            'email',
            'contact',
            'matricule',
            'etat',
        ]
        
class ProjetForm(forms.ModelForm):
    class Meta:
        model = Projet
        fields = [
            'sigle',
            'titre',
            'date_debut',
            'date_fin',
            'etat',
            'logo_partenaire',
            'logo_sarl',
        ]
        
class AttributionForm(forms.ModelForm):
    class Meta:
        model = Attribution
        fields = [
            'date_attribution',
        ]
        
        
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = [
            'motif',
            'depart',
            'destination',
            'date_course',
            'etat_course',
            'employe',
            'vehicule',
        ]

class MissionForm(forms.ModelForm):
    class Meta:
        model = Mission
        fields = [
            'objet',
            'reference',
            'localite',
            'matriculeLouer',
            'concessionnaire',
            'date_depart',
            'date_retour',
            'employe',
            'projet',
        ]
        

gestions/views.py
from ast import Str
import datetime
from django.contrib.staticfiles import finders
import os
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from engins.models import Engins
from gestions.forms import CourseForm, EmployeForm, ProjetForm
from django.contrib import messages
from xhtml2pdf import pisa

from gestions.models import Course, Employer, Mission, Projet
from django.template.loader import get_template, render_to_string
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='compteuser:login')
def EmployeView(request):
    employes = Employer.objects.all()
    
    context = {
        'employes':employes
    }
    return render(request, 'empl/employe.html',context)

@login_required(login_url='compteuser:login')
def Ajout_employe(request):
    form = EmployeForm()
    if request.method == 'POST':
        forms = EmployeForm(request.POST, request.FILES)
        if forms.is_valid():
            forms.save()
            messages.success(request, "Enregistrement effectué avec succèss !")
            return HttpResponseRedirect(reverse('gestions:employes'))
        else :
            messages.error(request, 'Attention ! Champs vide ou Matricule exite déja')
    
    context = {
        'form':form
    }
    
    return render(request, 'empl/ajout_emp.html',context)


@login_required(login_url='compteuser:login')
def Edit_employe(request, id= None):
    employe = Employer.objects.get(id= id)
    form = EmployeForm(request.POST or None, request.FILES or None, instance=employe)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Mise à jour effectué avec succèss !")
            return HttpResponseRedirect(reverse('gestions:employes'))
            
    context = {
        'form':form,
        'employe':employe
    }
    
    return render(request, 'empl/edit_emp.html',context)



@login_required(login_url='compteuser:login')
def ProjetView(request):
    projets = Projet.objects.all()
    
    context = {
        'projets':projets
    }
    
    return render(request, 'proj/projet.html',context)


@login_required(login_url='compteuser:login')
def Ajout_projet(request):
    form = ProjetForm()
    if request.method == 'POST':
        forms = ProjetForm(request.POST, request.FILES)
        if forms.is_valid():
            forms.save()
            messages.success(request, "Enregistrement effectué avec succèss !")
            return HttpResponseRedirect(reverse('gestions:projets'))
    
    context = {
        'form':form
    }
    
    return render(request, 'proj/ajout_proj.html',context)



@login_required(login_url='compteuser:login')
def Edit_projet(request, id =None):
    projet = Projet.objects.get(id=id)
    form = ProjetForm(request.POST or None, request.FILES or None, instance=projet)
    
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Mise à jour effectué avec succèss !")
          
    
    context = {
        'form':form,
        'projet':projet
    }
    return render(request, 'proj/edit_proj.html',context)



@login_required(login_url='compteuser:login')
def CoursesView(request):
    courses = Course.objects.order_by('-id')
    
    for course in courses :
        # print(course.id)
        time = datetime.datetime.now()
        if course.created_at.day == time.day:
            reduct = time.hour - course.created_at.hour
            if reduct >= 1 :
                course.diff = str(time.hour - course.created_at.hour) + " heurs"
            else :
                course.diff = "Moins d'une heure"
        else:
            if course.created_at.month == time.month:
                course.diff = str(time.day - course.created_at.day) + " jours"
            else:
                if course.created_at.year == time.year:
                    course.diff = str(time.month - course.created_at.month) + " mois"
                    
    context = {
        'courses':courses
    }
    
    return render(request, 'course/index.html',context)



@login_required(login_url='compteuser:login')
def Ajout_course(request):
    vehicules = Engins.objects.filter(etat = 'DISPONIBLE')
    employes = Employer.objects.filter(etat = 'EN ACTIVITE')
    
    if request.method == 'POST':
        course = Course()
        course.depart = request.POST['depart']
        course.destination = request.POST['destination']
        course.date_course = request.POST['date_course']
        course.etat_course = request.POST['etat_course']
        course.motif = request.POST['motif']
        course.employe_id = int(request.POST['employe'])
        course.vehicule_id = int(request.POST['vehicule'])
        course.save()
        
        engin = Engins.objects.get(id = course.vehicule.id)
        engin.etat = 'OCCUPE'
        engin.save()
        
        user = Employer.objects.get(id = course.employe.id)
        user.etat = 'OCCUPE'
        user.save()
        
        messages.success(request, "Enregistrement effectué avec succèss !")
        return HttpResponseRedirect(reverse('gestions:courses'))
        
    context = {
        'vehicules':vehicules,
        'employes':employes,
    }
    
    return render(request, 'course/ajout_course.html',context)



@login_required(login_url='compteuser:login')
def Edit_course(request,id =None):
    course = Course.objects.get(id= id)
    
    context = {
        'course':course
    }
    
    return render(request, 'course/edit_course.html',context)


@login_required(login_url='compteuser:login')
def Delete_course(request, id=None):
    course = Course.objects.get(id=id)
    
    engin = Engins.objects.get(id = course.vehicule.id)
    engin.etat = 'DISPONIBLE'
    engin.save()
    
    user = Employer.objects.get(id = course.employe.id)
    user.etat = 'EN ACTIVITE'
    user.save()
    
    course.delete()
    messages.success(request, "Suppression effectué avec succèss !")
    return HttpResponseRedirect(reverse('gestions:courses'))



@login_required(login_url='compteuser:login')
def Termine_course(request,id = None):
    course = Course.objects.get(id=id)
    course.etat_course = 'TERMINER'
    course.date_fin = datetime.datetime.now()
    course.save()
    
    engin = Engins.objects.get(id = course.vehicule.id)
    engin.etat = 'DISPONIBLE'
    engin.save()
    
    user = Employer.objects.get(id = course.employe.id)
    user.etat = 'EN ACTIVITE'
    user.save()
    


@login_required(login_url='compteuser:login')  
def MissionView(request):
    missions = Mission.objects.all()
    today = datetime.date.today()
    for mission in missions :        
        mission.diff = mission.date_retour.day - mission.date_depart.day
    
    
    context = {
        'missions':missions,
        'today':today
    }
    
    return render(request, 'mission/index.html', context)



@login_required(login_url='compteuser:login')
def Ajout_mission(request):
    projets = Projet.objects.filter(etat = 'EN COURS')
    employes = Employer.objects.filter(etat = 'EN ACTIVITE')
    vehicules = Engins.objects.filter(etat = 'DISPONIBLE')
    
    if request.method == 'POST':
        mission = Mission()
        if request.POST['moyen'] == 'NON' :
            mission.concessionnaire = request.POST['concessionnaire']
            mission.matriculeLouer = request.POST['matriculeLouer']
            mission.moyentransport = "VEHICULE DE LOCATION"
        elif request.POST['moyen'] == 'OUI':
            course = Course()
            course.etat_course = "EN COURS"
            course.motif = request.POST['objet']
            course.depart = request.POST['depart']
            course.destination = request.POST['destination']
            course.date_course = request.POST['date_depart']
            course.vehicule_id = request.POST['vehicule']
            course.employe_id = request.POST['chauffeur']
            course.save()
            
            engin = Engins.objects.get(id = course.vehicule.id)
            engin.etat = 'OCCUPE'
            engin.save()
            
            user = Employer.objects.get(id = course.employe.id)
            user.etat = 'OCCUPE'
            user.save()
            
            mission.course_id = course.id
            mission.moyentransport = "VEHICULE DE SERVICE"
        else:
            return HttpResponseRedirect(reverse('gestions:ajout_mission'))
   
        
        mission.objet = request.POST['objet']
        mission.reference = "/AGRO-MAP/SL/"+str(datetime.datetime.now().year)+"-"+str(datetime.datetime.now().month)
        mission.date_depart = request.POST['date_depart']
        mission.date_retour = request.POST['date_retour']
        mission.localite = request.POST['localite']
        mission.employe_id = request.POST['employe']
        mission.projet_id = request.POST['projet']
        mission.etat_mission = "EN COURS"
        mission.save()
        user = Employer.objects.get(id = mission.employe.id)
        user.etat = 'OCCUPE'
        user.save()
        messages.success(request, "Mission enregistrer avec succèss !")
        return HttpResponseRedirect(reverse('gestions:missions'))
    
        
    context = {
        'projets':projets,
        'employes':employes,
        'vehicules':vehicules,
        
    }
    
    return render(request, 'mission/ajout_mission.html', context)
            


@login_required(login_url='compteuser:login')
def Edit_mission(request, id= None):
    mission = Mission.objects.get(id= id)
    projets = Projet.objects.filter(etat = 'EN COURS')
    employes = Employer.objects.filter(etat = 'EN ACTIVITE')
    vehicules = Engins.objects.filter(etat = 'DISPONIBLE')
    
    context = {
        "mission":mission,
        "projets":projets,
        "employes":employes,
        "vehicules":vehicules
    }
    

gestions/templates/mission/edit_mission.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">DETAILS MISSIONS</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">

            <div class="row">
                <h4>INFO MISSION</h4>
                <div class="col-md-4 mt-3" >
                    <strong>OBJET DE LA MISSION : </strong> <br>
                    <strong>DONNE L'ORDRE A  : </strong><br>
                    <strong>FONCTION : </strong><br>
                    <strong>DE SE RENDRE EN MISSION A : </strong><br>
                    <strong>MOYEN DE TRANSPORT : </strong><br>
                    <strong>DATE DE DEPART : </strong><br>
                    <strong>DATE DE RETOUR : </strong><br>
                    <strong>ETAT DE LA MISSION : </strong><br>
                    <strong>IMPUTATION BUDGETAIRE : </strong><br>
                </div>
                <div class="col-md-6 mt-3" >
                    <strong>{{mission.objet}}</strong> <br>
                    <strong>{{mission.employe.nom}} {{mission.employe.prenom}}</strong><br>
                    <strong>{{mission.employe.fonction.libelle}}</strong><br>
                    <strong>{{mission.localite}}</strong><br>
                    <strong> {{mission.moyentransport}}</strong><br>
                    <strong>{{mission.date_depart}}</strong><br>
                    <strong> {{mission.date_retour}}</strong><br>
                    <strong> {{mission.etat_mission}}</strong><br>
                    <strong>{{mission.projet.sigle}} {% if mission.projet.logo_partenaire %}<img src="http://127.0.0.1:8000/static{{mission.projet.logo_partenaire.url}}" class="mr-2" alt="Profile Page" width="70px" height="30px" style="border: 1px solid #ddd;">{% endif %} </strong><br>
                </div>
                <div class="col-md-2 mt-3" >
                    <a href="{% url 'gestions:print_mission_pdf' mission.id %}" class="btn btn-primary btn-sm mb-2">IMPRIMER MISSION (PDF)</a> <br>
                    {% if mission.etat_mission == 'EN COURS' %}
                        <a onclick="termine_mission('{% url 'gestions:finir_mission' mission.id %}')" class="btn btn-warning btn-sm mb-2">FINIR MISSION </a> <br> 
                    {% endif %}
                    <a href="{% url 'gestions:delete_mission' mission.id %}" class="btn btn-danger btn-sm">SUPPRIMER MISSION </a> <br> 
                   
                     
                </div>
          
            </div>
            
        </div>
      </div>
    </div>
</div>

{% comment %} <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">

            <div class="row">
                <h4>AUTRES INFOS</h4>
                <div class="col-md-2">
                    {% if course.vehicule.engin_image %}
                        <img src="http://127.0.0.1:8000/static{{course.vehicule.engin_image.url}}" class="mr-2" alt="Profile Page" width="200px" height="200px" style="border: 1px solid #ddd;">
                    {% else %}
                    <img src="" class="mr-2" alt="NO IMAGE" width="200px" height="200px" style="border: 1px solid #ddd;">
                    {% endif %}
                    
                </div>
                <div class="col-md-6 mt-3" >
                    <strong>MARQUE : {{course.vehicule.marque}}</strong> <br>
                    <strong>MODEL : {{course.vehicule.model}}</strong><br>
                    <strong>MATRICULE : {{course.vehicule.matricule}}</strong><br>
                    <strong>NUMERO DE CHARSIS : {{course.vehicule.numcharsis}}</strong><br>
                </div>

                <div class="col-md-4 mt-3" >
                    <h6><u>Utilisateur </u></h6>
                    <strong>NOM : {{course.employe.nom}}</strong> <br>
                    <strong>PRENOMS : {{course.employe.prenom}}</strong><br>
                    <strong>FONCTION : {{course.employe.fonction}}</strong><br>
                    <strong>CONTACT : {{course.employe.contact}}</strong><br>
                </div>
          
            </div>
            
        </div>
      </div>
    </div>
</div> {% endcomment %}




{% endblock %}

gestions/templates/mission/index.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">MISSIONS</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="container-fluid">
 <div class="row">
    <div class="col-12"> 
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Listes des missions</h5>

        {% if messages %}
        <div class="alert alert-success text-center alert-dismissible " role="alert">
            
            <ul class="messages">
                {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                {% endfor %}
            </ul>
            
        </div>
        {% endif %}


      <div class="table-responsive">
        <a href="{% url 'gestions:ajout_mission' %}" class="btn btn-primary" style="float: right; margin-right: 20px;" > Ajouter </a>
        <table id="zero_config" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th style="max-width: 100px;">Ordre à </th>
              <th style="max-width: 100px;">OBJET </th>
              <th style="max-width: 100px;">LOCALITE</th>
              <th style="max-width: 100px;">MOYEN DE TRANSPORT</th>
              <th style="max-width: 100px;">ETAT</th>
              <th style="max-width: 100px;">DATE DE DEPART</th>
              <th style="max-width: 100px;">DUREE DE MISSION</th>
              <th style="max-width: 100px;">PROJET</th>
              <th style="max-width: 100px;">ACTION</th>
            </tr>
          </thead>
          <tbody>
            {% for mission in missions %}
            <tr {% if mission.date_retour < today and mission.etat_mission == "EN COURS" %} style="background-color: #fce3e3;" {% endif %}  >
                <td>{{mission.employe.nom}} {{mission.employe.prenom}}</td>
                <td>{{mission.objet}}</td>
                <td>{{mission.localite}}</td>
                <td>{{mission.moyentransport}}</td>
                <td>{{mission.etat_mission}}</td>
                <td>{{mission.date_depart}}</td>
                <td>{{mission.diff }} jour(s)</td>
                <td>{{mission.projet}}</td>
                <td>    
                        <a href="{% url 'gestions:edit_mission' mission.id %}" class="btn btn-primary btn-sm" >Voir </a>
                    {% if mission.etat_mission == 'EN COURS' %}
                        <a  onclick="termine_mission('{% url 'gestions:finir_mission' mission.id %}')" class="btn btn-danger btn-sm">Terminer </a>
                    {% endif %}
                    
                </td>
              </tr>
            {% endfor %}


          </tfoot>
        </table>
      </div>
    </div>
  </div>

  </div>
  </div>
  </div>
{% endblock %}

gestions/templates/mission/mission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
        <title>LOGISTIQUE|MISSION {{mission.id}}</title>
        <style>
            table.GeneratedTable {
                background-image: url('https://fpmpro.pythonanywhere.com/static/img/Logo.jpg');
                width: 100%;
                background-color: #ffffff;
                border-collapse: collapse;
                border-width: 2px;
                border-color: #ffcc00;
                border-style: solid;
                color: #000000;
                font-size: 13px;
            }
    
            table.GeneratedTable td, table.GeneratedTable th {
                border-width: 2px;
                border-color: black;
                border-style: solid;
                padding: 3px;
            }
    
            table.GeneratedTable thead {
                background-color: #525252;
                color: white;
            }
            table.table2{
                width: auto;
                background-color: #ffffff;
                border-collapse: collapse;
                border-width: 2px;
                border-color: #ffcc00;
                border-style: solid;
                color: white;
                font-size: 13px;
            }
            table.table2 td{
                border-width: 2px;
                border-color: black;
                border-style: solid;
                padding: 5px;
                font-weight: bold;
            }
            table.table2 tr td:nth-child(1){
                background-color: #757474;
                color: white;
            }
            table.table2 tr td:nth-child(2), table.table1 tr td:nth-child(2){
                text-align: center;
            }
            table.table1{
                width: 100%;
                background-color: #ffffff;
                border-collapse: collapse;
                border-width: 2px;
                border-color: #ffcc00;
                border-style: solid;
                color: #000000;
                font-size: 13px;
            }
            table.table1 td{
                border-width: 2px;
                border-color: black;
                border-style: solid;
                padding: 3px;
                font-weight: bold;
            }
            .text-danger{
                color: #f13030;
            }
            #footer {
                position: relative;
                margin-top: 700px;
            }
            .float-right{
                float: right;
                margin-right: 0 !important;
            }
            .fw-b{
                font-weight: bold;
                right: 0;
            }
            .tb-type-coti thead tr {
                background-color: grey;
                border: 1px solid black;
                color: white;
                text-align: left;
            }
            .tb-type-coti tr td{
                border-width: 2px;
                border-color: #030303;
            }
            .tfoot td{
                color: red;
                font-weight: bold;
            }
        </style>
    </head>
</head>
<body>
    <table class="info-asso" width="100%">
        <thead>
            <tr>
                <td  width="20%">
                  {% if mission.projet.logo_partenaire %} <img src="http://127.0.0.1:8000/static{{mission.projet.logo_partenaire.url}}" alt="logo" height="100" width="100"> {% endif %}  <br>
                </td>
                <td width="60%" style="text-align: center">
                    <h1 style="font-weight: bold; text-transform: capitalize; font-size:25px">
                        TERMES DE REFERENCE DE MISSION N° {{mission.id}}
                    </h1>
                </td>
                <td  width="20%">
                  {% if mission.projet.logo_sarl %}<img src="http://127.0.0.1:8000/static{{mission.projet.logo_sarl.url}}" alt="logo" height="100" width="100">{% endif %}  <br>

                    <b style="margin-top: 10px">
                        Fait Abidjan le: {% now  ''%}<br>
                    </b>
                    <br>
                </td>
            </tr>
        </thead>
    </table>
    <br>
    <br>
    <div style="text-align: center; border : solid;"><h1 style="margin-bottom: 60px; padding :10px;">ORDRE DE MISSION</h1></div>

    <div>
        <h2><strong><u>Ref</u> : ......................................{{mission.reference}}</strong></h2>
    </div>

    <br>
    <table class="info-asso" width="100%" >
        <thead>
            <tr style="margin-bottom: 45px;">
                <td width="40%"> <h3 style="font-size: 14px;">Donne l'ordre à :</h3>  </td>
                <td width="60%"> <h3 style="font-size: 17px;"><strong>{{mission.employe.nom}} {{mission.employe.prenom}}</strong></h3> </td>
            </tr> 
            <tr>
                <td width="40%"> <h3 style="font-size: 14px;">Fonction :</h3>  </td>
                <td width="60%"> <h3 style="font-size: 17px;"><strong>{{mission.employe.fonction}}</strong></h3> </td>
            </tr>
            <tr>
                <td width="40%"> <h3 style="font-size: 14px;">Destination :</h3>  </td>
                <td width="60%"> <h3 style="font-size: 17px;"><strong>{{mission.localite}}</strong></h3> </td>
            </tr>
            <tr>
                <td width="40%"> <h3 style="font-size: 14px;">Objet de la mission :</h3>  </td>
                <td width="60%"> <h3 style="font-size: 17px;"><strong>{{mission.objet}}</strong></h3> </td>
            </tr>
            <tr>
                <td width="40%"> <h3 style="font-size: 14px;">Moyen de transport :</h3>  </td>
                <td width="60%"> <h3 style="font-size: 17px;"><strong>{{mission.moyentransport}}</strong></h3> </td>
            </tr> 
            <tr>
                <td width="40%"> <h3 style="font-size: 14px;">Info du véhicule :</h3>  </td>
                <td width="60%"> <h3 style="font-size: 17px;"><strong>
                    {% if not mission.matriculeLouer %}
                        {{mission.course.vehicule.matricule}} / {{mission.course.vehicule.marque}} {{mission.course.vehicule.model}}
                    {% else %}
                        {{mission.matriculeLouer}}
                    {% endif %}
                    
                </strong></h3> </td>
            </tr>
            <tr>
                <td width="40%"> <h3 style="font-size: 14px;">Date de depart :</h3>  </td>
                <td width="60%"> <h3 style="font-size: 17px;"><strong>{{mission.date_depart}}</strong></h3> </td>
            </tr>
            <tr>
                <td width="40%"> <h3 style="font-size: 14px;">Date de retour :</h3>  </td>
                <td width="60%"> <h3 style="font-size: 17px;"><strong>{{mission.date_retour}}</strong></h3> </td>
            </tr>
            <tr>
                <td width="40%"> <h3 style="font-size: 14px;">Imputation budgétaire :</h3>  </td>
                <td width="60%"> <h3 style="font-size: 17px;"><strong>{{mission.projet.sigle}}</strong></h3> </td>
            </tr>
        </thead>
    </table>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <h2 style="margin-left : 500px;"><u>DIRECTEUR GENERAL</u></h2>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h2 style="margin-left : 500px;">ADAYE KOUAME PATRICE</h2>
    
</body>
</html>