engins/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from engins.views import AjoutCarView, DeleteCars, EditCarView, home

app_name = "engins"

urlpatterns = [
    path('', home, name='home'),
    path('ajout_car/', AjoutCarView, name='ajout_car'),
    path('edit_car/<int:id>', EditCarView, name='edit_car'),
    path('delete_car/<int:id>', DeleteCars, name='deletecar'),
]

logistics/urls.py
from django.contrib import admin
from django.urls import include, path
from parametres.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('parametre/', include('parametres.urls')),
    path('engins/', include('engins.urls')),
    path('equipements/', include('equipements.urls')),
    path('gestions/', include('gestions.urls')),
    path('auth/',include('compteuser.urls')),
    path('', index, name='index'),
]

parametres/urls.py
from django.urls import path, include

from parametres.views import delFonction, delTymateriel, delVehicule, fonctionhomne, typeMaterialhomne, typeVehiculehomne, upFonction, upTymateriel, upVehicule, updateFonction, updateTymateriel, updateVehicule

app_name = "parametres"

urlpatterns = [
    path('fonction/', fonctionhomne, name='fonction'),
    path('type-material/', typeMaterialhomne, name='typem'),
    path('type-vehicule/', typeVehiculehomne, name='tyvehicule'),
    
    path('del-fonction/<int:id>', delFonction, name='delfonction'),
    path('up-fonction/<int:id>', upFonction, name='upfonction'),
    path('update-fonction/', updateFonction, name='update_fonction'),
    
    path('del-tymateriel/<int:id>', delTymateriel, name='deltymateriel'),
    path('up-tymateriel/<int:id>', upTymateriel, name='uptymateriel'),
    path('update-tymateriel/', updateTymateriel, name='update_tymateriel'),    
    
    path('del-delvehicule/<int:id>', delVehicule, name='delvehicule'),
    path('up-vehicule/<int:id>', upVehicule, name='upvehicule'),
    path('update-vehicule/', updateVehicule, name='update_vehicule'),

    
    
    # path('', connexion, name='connexion'),
    # path('inscription/', inscription, name='inscription'),
    # path('deconnexion/', deconnexion, name='deconnexion'),
    # path('responsables/', responsable, name='responsables'),
    # path('projets/', projet, name='projets'),
    # path('add_projet/', add_projet, name='add_projet'),
    # path('techniciens/', technicien, name='techniciens'),
    # path('add_technicien/', add_technicien, name='add_technicien'),
    # path('projet/<int:id>', detail_projet, name='detail_projet'),
    # path('accueil/', index, name='index'),
]

parametres/models.py
from django.db import models

# Create your models here.

class Fonction(models.Model):
    libelle = models.CharField(max_length=225,unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return '%s' % (self.libelle)

    def save(self, force_insert=False, force_update=False):
        self.libelle = self.libelle.upper()
        super(Fonction, self).save(force_insert, force_update)
        
        
class Type_vehicule(models.Model):
    libelle = models.CharField(max_length=225,unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return '%s' % (self.libelle)

    def save(self, force_insert=False, force_update=False):
        self.libelle = self.libelle.upper()
        super(Type_vehicule, self).save(force_insert, force_update)
        

class Type_materiel(models.Model):
    libelle = models.CharField(max_length=225,unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return '%s' % (self.libelle)

    def save(self, force_insert=False, force_update=False):
        self.libelle = self.libelle.upper()
        super(Type_materiel, self).save(force_insert, force_update)

parametres/forms.py
from django import forms
from parametres.models import Fonction,Type_materiel, Type_vehicule

class FonctionForm(forms.ModelForm):
    class Meta:
        model = Fonction
        fields = [
            'libelle',
        ]
        
class Type_materialForm(forms.ModelForm):
    class Meta:
        model = Type_materiel
        fields = [
            'libelle',
        ]
        
class Type_vehiculeForm(forms.ModelForm):
    class Meta:
        model = Type_vehicule
        fields = [
            'libelle',
        ]

parametres/views.py
from pyexpat.errors import messages
from turtle import back
import datetime
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from engins.models import Engins
from equipements.models import Materiel
from gestions.models import Employer, Mission, Projet
from parametres.forms import FonctionForm, Type_materialForm, Type_vehiculeForm

from parametres.models import Fonction, Type_materiel, Type_vehicule
from django.contrib import messages
from django.template.loader import get_template, render_to_string
from django.template.context_processors import csrf
from xhtml2pdf import pisa
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='compteuser:login')
def index(request):
    today = datetime.date.today()
    missions = Mission.objects.filter(etat_mission = "EN COURS").order_by('-id')[:10]
    engins = Engins.objects.filter(etat = "DISPONIBLE")

    nb_mission_en_cours = len(Mission.objects.filter(etat_mission = "EN COURS"))
    nb_vehicule_disponible = len(Engins.objects.filter(etat = "DISPONIBLE") & Engins.objects.filter(type_engins = 2))
    nb_moto_disponible = len(Engins.objects.filter(etat = "DISPONIBLE") & Engins.objects.filter(type_engins = 1)) + len(Engins.objects.filter(etat = "DISPONIBLE") & Engins.objects.filter(type_engins = 3))
    nb_voiture_garage = len(Engins.objects.filter(etat = "OCCUPE") & Engins.objects.filter(type_engins = 2))
    nb_moto_garage = len(Engins.objects.filter(etat = "OCCUPE") & Engins.objects.filter(type_engins = 1))
    nb_tois_roue_garage = len(Engins.objects.filter(etat = "OCCUPE") & Engins.objects.filter(type_engins = 3) )
    nb_employe_activite = len(Employer.objects.filter(etat = "EN ACTIVITE")) + len(Employer.objects.filter(etat = "OCCUPE"))
    nb_projet_en_cours = len(Projet.objects.filter(etat = "EN COURS"))
    nb_equipement_gps_fonctionnelle = len(Materiel.objects.filter(etat = "FONCTIONNELLE") & Materiel.objects.filter(type_materiel = 2)) + len(Materiel.objects.filter(etat = "ATTRIBUER") & Materiel.objects.filter(type_materiel = 2))
    nb_equipement_ordi_fonctionnelle = len(Materiel.objects.filter(etat = "FONCTIONNELLE") & Materiel.objects.filter(type_materiel = 1)) + len(Materiel.objects.filter(etat = "ATTRIBUER") & Materiel.objects.filter(type_materiel = 1))
    
    context = {
        'missions': missions,
        'engins': engins,
        'nb_mission_en_cours':nb_mission_en_cours,
        'nb_vehicule_disponible':nb_vehicule_disponible,
        'nb_moto_disponible':nb_moto_disponible,
        'nb_voiture_garage':nb_voiture_garage,
        'nb_moto_garage':nb_moto_garage,
        'nb_tois_roue_garage':nb_tois_roue_garage,
        'nb_employe_activite':nb_employe_activite,
        'nb_projet_en_cours':nb_projet_en_cours,
        'nb_equipement_gps_fonctionnelle':nb_equipement_gps_fonctionnelle,
        "today":today,
        "nb_equipement_ordi_fonctionnelle":nb_equipement_ordi_fonctionnelle
    }
    return render(request, 'pages/home.html', context)
   
@login_required(login_url='compteuser:login')
def fonctionhomne(request):
    fonctions = Fonction.objects.all()
    form = FonctionForm()
    error = ''
    if request.method == 'POST':
        forms = FonctionForm(request.POST)
        if forms.is_valid():
            forms.save()
            messages.success(request, 'Enregistrement effectué avec succèss !')
        else:
            error = 'Attention ! Champs vide ou libelle exite déja'
            messages.error(request, 'Attention ! Champs vide ou libelle exite déja')
            
    context = {
        'fonctions':fonctions,
        'form':form,
        'error':error
    }
    
    return render(request,'fonction.html',context)

@login_required(login_url='compteuser:login')
def typeMaterialhomne(request):
    tymateriels = Type_materiel.objects.all()
    form = Type_materialForm()
    error = ''
    if request.method == 'POST':
        forms = Type_materialForm(request.POST)
        if forms.is_valid():
            forms.save()
            messages.success(request, 'Enregistrement effectué avec succèss !')
        else:
            error = 'Attention ! Champs vide ou libelle exite déja'
            messages.error(request, 'Attention ! Champs vide ou libelle exite déja')
            
    context = {
        'tymateriels':tymateriels,
        'form':form,
        'error':error
    }
    return render(request,'tymaterial.html',context)

@login_required(login_url='compteuser:login')
def typeVehiculehomne(request):
    tyvehicules = Type_vehicule.objects.all()
    form = Type_vehiculeForm()
    error = ''
    if request.method == 'POST':
        forms = Type_vehiculeForm(request.POST)
        if forms.is_valid():
            forms.save()
            messages.success(request, 'Enregistrement effectué avec succèss !')
        else:
            error = 'Attention ! Champs vide ou libelle exite déja'
            messages.error(request, 'Attention ! Champs vide ou libelle exite déja')
    
    context = {
        'tyvehicules':tyvehicules,
        'form':form,
        'error':error
    }
    return render(request,'tyvehicule.html',context)



@login_required(login_url='compteuser:login')
def delFonction(request, id= None):
    fonction = Fonction.objects.get(id=id)
    fonction.delete()
    messages.success(request, "Lélément "+fonction.libelle+" a été supprimé avec succès")
    return HttpResponseRedirect(reverse('parametres:fonction'))


@login_required(login_url='compteuser:login')
def upFonction(request, id= None):
    fonction = Fonction.objects.get(id=id)
    form = FonctionForm(request.POST or None, request.FILES or None, instance=fonction)
    context = {
        'fonction':fonction,
        'form':form
    }
    context.update(csrf(request))
    templateStr = render_to_string("modal/edit_fonction.html", context)
    return JsonResponse({'templateStr':templateStr,'id':id},safe=False)



@login_required(login_url='compteuser:login')
def updateFonction(request):
    id = request.POST['fonct']
    fonction = Fonction.objects.get(id=int(id))
    fonction.libelle = request.POST['libelle']
    fonction.save()
    messages.success(request, "Lélément "+fonction.libelle+" a été modifié avec succès")
    return HttpResponseRedirect(reverse('parametres:fonction'))



@login_required(login_url='compteuser:login')
def delTymateriel(request,id=None):
    tymateriel = Type_materiel.objects.get(id=id)
    tymateriel.delete()
    messages.success(request, "Lélément "+tymateriel.libelle+" a été supprimé avec succès")
    return HttpResponseRedirect(reverse('parametres:typem'))
    
 
 
@login_required(login_url='compteuser:login')   
def upTymateriel(request, id= None):
    tymateriel = Type_materiel.objects.get(id=id)
    form = Type_materialForm(request.POST or None, request.FILES or None, instance=tymateriel)
    context = {
        'tymateriel':tymateriel,
        'form':form
    }
    context.update(csrf(request))
    templateStr = render_to_string("modal/edit_tymateriel.html", context)
    return JsonResponse({'templateStr':templateStr,'id':id},safe=False)




@login_required(login_url='compteuser:login')
def updateTymateriel(request):
    id = request.POST['tymateriel']
    tymateriel = Type_materiel.objects.get(id=int(id))
    tymateriel.libelle = request.POST['libelle']
    tymateriel.save()
    messages.success(request, "Lélément "+tymateriel.libelle+" a été modifié avec succès")
    return HttpResponseRedirect(reverse('parametres:typem'))


@login_required(login_url='compteuser:login')
def delVehicule(request,id=None):
    vehicule = Type_vehicule.objects.get(id=id)
    vehicule.delete()
    messages.success(request, "Lélément "+vehicule.libelle+" a été supprimé avec succès")
    return HttpResponseRedirect(reverse('parametres:tyvehicule'))


@login_required(login_url='compteuser:login')
def upVehicule(request, id= None):
    vehicule = Type_vehicule.objects.get(id=id)
    form = Type_vehiculeForm(request.POST or None, request.FILES or None, instance=vehicule)
    context = {
        'vehicule':vehicule,
        'form':form
    }
    context.update(csrf(request))
    templateStr = render_to_string("modal/edit_vehicule.html", context)
    return JsonResponse({'templateStr':templateStr,'id':id},safe=False)



@login_required(login_url='compteuser:login')
def updateVehicule(request):
    id = request.POST['vehicule']
    vehicule = Type_vehicule.objects.get(id=int(id))
    vehicule.libelle = request.POST['libelle']
    vehicule.save()
    messages.success(request, "Lélément "+vehicule.libelle+" a été modifié avec succès")
    return HttpResponseRedirect(reverse('parametres:tyvehicule'))







######-------------------------------------------------------MPI----------------------------01/08/2022-------------------------------------------------

parametres/templates/fonction.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">FONCTIONS</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="container-fluid">
 <div class="row">
    <div class="col-12"> 
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Listes des fonctions</h5>
      {% if error == '' %}
        {% if messages %}
        <div class="alert alert-success text-center alert-dismissible " role="alert">
            
            <ul class="messages">
                {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                {% endfor %}
            </ul>
            
        </div>
        {% endif %}
    {% endif %}

    {% if error != '' %}
    <div class="alert alert-danger text-center alert-dismissible " role="alert">
        <ul class="messages">
            {% for message in messages %}
            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
      <div class="table-responsive">
        <button type="button" class="btn btn-primary" style="float: right; margin-right: 20px;" data-bs-toggle="modal" data-bs-target="#exampleModal"> Ajouter </button>
        <table id="zero_config" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>LIBELLE</th>
              <th style="max-width: 50px;">ACTION</th>
            </tr>
          </thead>
          <tbody>
            {% for fonc in fonctions %}
            <tr>
                <td>{{fonc.libelle}}</td>
                <td>    
                    <a class="btn btn-primary btn-sm" onclick="edit('{% url 'parametres:upfonction' fonc.id %}')">Modifier </a>
                    {% comment %} <a href="{% url 'parametres:delfonction' fonc.id %}" class="btn btn-danger btn-sm">Supprimer </a> {% endcomment %}
                </td>
              </tr>
            {% endfor %}


          </tfoot>
        </table>
      </div>
    </div>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Enregistrer une fonction</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="" method="post"  id="form" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label>Libelle</label>
                    {% render_field form.libelle type="text" class="form-control" %}
                    <span class="code_error text-danger"></span>
                </div>
           
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
          <button type="submit" class="btn btn-primary">Enregistrer</button>
        </div>
    </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="Modal" aria-hidden="true">

  </div>

  </div>
  </div>
  </div>
    
{% endblock %}

parametres/templates/tymaterial.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">TYPE MATERIEL</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="container-fluid">
 <div class="row">
    <div class="col-12"> 
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Listes des types de matériaux</h5>
      {% if error == '' %}
      {% if messages %}
      <div class="alert alert-success text-center alert-dismissible " role="alert">
          
          <ul class="messages">
              {% for message in messages %}
              <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
              {% endfor %}
          </ul>
          
      </div>
      {% endif %}
  {% endif %}

  {% if error != '' %}
  <div class="alert alert-danger text-center alert-dismissible " role="alert">
      <ul class="messages">
          {% for message in messages %}
          <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
          {% endfor %}
      </ul>
  </div>
  {% endif %}
      <div class="table-responsive">
        <button type="button" class="btn btn-primary" style="float: right; margin-right: 20px;" data-bs-toggle="modal" data-bs-target="#exampleModal"> Ajouter </button>
        <table id="zero_config" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>LIBELLE</th>
              <th style="max-width: 50px;">ACTION</th>
            </tr>
          </thead>
          <tbody>
            {% for tymateriel in tymateriels %}
              <tr>
                <td>{{tymateriel.libelle}}</td>
                <td>
                  <a class="btn btn-primary btn-sm" onclick="edit('{% url 'parametres:uptymateriel' tymateriel.id %}')">Modifier </a>
                  {% comment %} <a href="{% url 'parametres:deltymateriel' tymateriel.id %}" class="btn btn-danger btn-sm">Supprimer </a> {% endcomment %}
                </td>
              </tr>
            {% endfor %}

          </tfoot>
        </table>
      </div>
    </div>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Enregistrer type matérial</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="" method="POST"  id="form" enctype="multipart/form-data" novalidate>
              {% csrf_token %}
                <div class="form-group">
                    <label>Libelle</label>
                    {% render_field form.libelle type="text" class="form-control" %}
                    <span class="code_error text-danger"></span>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                  <button type="submit" class="btn btn-primary">Enregistrer</button>
                </div>

        </div>

    </form>
      </div>
    </div>
  </div>
  <div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="Modal" aria-hidden="true">

  </div>
  </div>
  </div>
  </div>
    
{% endblock %}

parametres/templates/tyvehicule.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block breadcumbs %}
    <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">TYPE D' ENGINS</h4>
            </div>
          </div>
        </div>
{% endblock %}

{% block content %}
<div class="container-fluid">
 <div class="row">
    <div class="col-12"> 
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Listes des Types d'engins</h5>
      {% if error == '' %}
      {% if messages %}
      <div class="alert alert-success text-center alert-dismissible " role="alert">
          
          <ul class="messages">
              {% for message in messages %}
              <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
              {% endfor %}
          </ul>
          
      </div>
      {% endif %}
  {% endif %}

  {% if error != '' %}
  <div class="alert alert-danger text-center alert-dismissible " role="alert">
      <ul class="messages">
          {% for message in messages %}
          <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
          {% endfor %}
      </ul>
  </div>
  {% endif %}
      <div class="table-responsive">
        <button type="button" class="btn btn-primary" style="float: right; margin-right: 20px;" data-bs-toggle="modal" data-bs-target="#exampleModal"> Ajouter </button>
        <table id="zero_config" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>LIBELLE</th>
              <th style="max-width: 25px;">ACTION</th>
            </tr>
          </thead>
          <tbody>
            {% for tyvehicule in tyvehicules %}
              <tr>
                <td>{{tyvehicule.libelle}}</td>
                <td>
                  <a class="btn btn-primary btn-sm" onclick="edit('{% url 'parametres:upvehicule' tyvehicule.id %}')">Modifier </a>
                  {% comment %} <a href="{% url 'parametres:delvehicule' tyvehicule.id %}" class="btn btn-danger btn-sm">Supprimer </a> {% endcomment %}
                </td>
              </tr>

            {% endfor %}

          </tfoot>
        </table>
      </div>
    </div>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Enregistrer un type engins</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="" method="POST" id="form" enctype="multipart/form-data" novalidate>
              {% csrf_token %}
                <div class="form-group">
                    <label>Libelle</label>
                    {% render_field form.libelle type="text" class="form-control" %}
                    <span class="code_error text-danger"></span>
                </div>
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
          <button type="submit" class="btn btn-primary">Enregistrer</button>
        </div>
    </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="Modal" aria-hidden="true">

  </div>

  </div>
  </div>
  </div>
    
{% endblock %}